[희택] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/29-westagram-backend-5-team pull request #14
Opened 2022-01-17 08:44 UTC by sosolyht

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- bcrypt 적용
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-17 08:46 UTC, wepungsan commented
LGTM :)

2022-01-17 09:10 UTC, bigfanoftim requested changes

2022-01-17 09:10 UTC, bigfanoftim commented on students/heetaek/westagram/users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
`bytes`로 저장하는 이유가 따로 있을까요 희택님?

2022-01-17 10:16 UTC, sosolyht commented on students/heetaek/westagram/users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
아직 이해가 안가는데 이해해보겠습니다,

2022-01-18 01:32 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-18 01:32 UTC, merged