[최형택] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/29-westagram-backend-5-team pull request #17
Opened 2022-01-18 08:57 UTC by knuckles6974

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-18 12:43 UTC, bigfanoftim requested changes
형택님! 기본적으로 하나의 PR에 하나의 기능만 올리는게 맞습니다. 다음부터 꼭 적용해주세요!

2022-01-18 12:43 UTC, bigfanoftim commented on students/hyeongtaek/westagram/users/views.py
> +                phone_number  = data['phone_number'],
지정하신 변수를 활용해주세요!
```suggestion
                name          = name,
                email         = email,
                password      = password,
                phone_number  = phone_number
```

2022-01-18 12:43 UTC, bigfanoftim commented on students/hyeongtaek/westagram/users/views.py
> +
이메일 중복 여부도 체크해주세요!
```python
if User.objects.filter(email = email).exists():
    return JsonResponse({'message' : 'EMAIL_ALREADY_EXISTS'}, status=400)
```

2022-01-20 00:48 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-20 00:48 UTC, merged