[이도운] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/29-westagram-backend-5-team pull request #7
Opened 2022-01-14 01:54 UTC by wepungsan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 뷰 구현
		 
## 수정 사항들 자세한 내용
- GET으로 데이터를 받아와서 데이터베이스 데이터와 비교한다.
- 비교가 완료되면 에러 메세지 혹은 로그인 성공 메세지를 반환한다

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-14 02:39 UTC, bigfanoftim requested changes
해당 PR은 로그인 기능에 관한 코드만 올라와야 합니다. 아직 merge 되지 않은 내용들이 올라와 있습니다. 다 삭제 후에 다시 올려주세요~

2022-01-17 02:17 UTC, lordmyshepherd commented
Mission 4부터는 피어리뷰 요청 라벨로 변경해주시고, 한명 이상의 동료가 리뷰를 완료한 경우에 멘토리뷰 라벨을 붙여주세요~

2022-01-17 03:47 UTC, sosolyht commented on students/dowoon/users/views.py
> +
```suggestion



```

2022-01-17 03:47 UTC, sosolyht commented on students/dowoon/users/views.py
> +
```suggestion



```
화이트스페이스 삭제 부탁드립니다!

2022-01-17 03:48 UTC, wepungsan commented on students/dowoon/users/views.py
> +
확인 / 수정했습니다

2022-01-17 05:10 UTC, bigfanoftim requested changes

2022-01-17 05:10 UTC, bigfanoftim commented on students/dowoon/users/views.py
> +            return JsonResponse({"message": "INVALID_USER (email)"}, status=401)
가독성을 위해 `try, except` 블록을 하나만 사용해주세요!

2022-01-17 05:10 UTC, bigfanoftim commented on students/dowoon/users/views.py
> +            return JsonResponse({"message": "SUCCESS"}, status=200)
굳이 `else`가 필요한게 아니기 때문에 지워주시는게 좋습니다!
```suggestion
        if password != user.password:
            return JsonResponse({"message": "INVALID_USER (password)"}, status=401)
            
        return JsonResponse({"message": "SUCCESS"}, status=200)
```

2022-01-17 06:48 UTC, wepungsan commented on students/dowoon/users/views.py
> +            return JsonResponse({"message": "INVALID_USER (email)"}, status=401)
확인 / 수정했습니다

2022-01-17 06:51 UTC, wepungsan commented on students/dowoon/users/views.py
> +            return JsonResponse({"message": "SUCCESS"}, status=200)
확인 / 수정했습니다

2022-01-17 07:33 UTC, bigfanoftim approved these changes
LGTM 👍

2022-01-17 07:33 UTC, merged