[희택] Mission3 . 회원가입 기능 구현
wecode-bootcamp-korea/29-westagram-backend-5-team pull request #8
Opened 2022-01-14 07:52 UTC by sosolyht

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 메인 urls 에 users app url 추가
- users urls 에 signup view 추가
- signup 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-14 08:12 UTC, lordmyshepherd requested changes

2022-01-14 08:12 UTC, lordmyshepherd commented on students/heetaek/westagram/users/validator.py
> +        return False
1. 정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.
2. `is_email`,`is_password`의 경우는 함수가 어떤 기능을 하는지 알기가 어렵습니다. 유효성 검사를 하는 함수인지 명확히 알 수 있도록 함수명을 수정 부탁드려요~

```python
REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def validate_email(value) :    
    if not re.match(REGEX_EMAIL, value):
        ...

def validate_password(value) :
    if not re.match(REGEX_EMAIL, value):
        ..
```

2022-01-14 08:12 UTC, lordmyshepherd commented on students/heetaek/westagram/users/views.py
> +                return JsonResponse({'message':'Password is not valid'}, status = 400)
```suggestion
            if not is_email(email):
                return JsonResponse ({'message':'E-mail is not valid'}, status = 400)

            if not is_password(password):
                return JsonResponse({'message':'Password is not valid'}, status = 400)
```

2022-01-14 08:39 UTC, bigfanoftim requested changes

2022-01-14 08:39 UTC, bigfanoftim commented on students/heetaek/westagram/users/validator.py
> +        return False
희택님! 주석으로 설명을 더하는게 아니라 피드백 내용처럼 함수명을 정확하게 작성해주세요~

2022-01-14 08:39 UTC, bigfanoftim commented on students/heetaek/westagram/users/views.py
> +class SignUp(View):
네이밍 컨벤션에 맞게 수정해주세요!
```suggestion
class SignUpView(View):
```

2022-01-14 08:57 UTC, sosolyht commented on students/heetaek/westagram/users/validator.py
> +        return False
수정완료하였습니다

2022-01-14 08:57 UTC, sosolyht commented on students/heetaek/westagram/users/views.py
> +class SignUp(View):
수정완료하였습니다

2022-01-17 02:13 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-01-17 02:13 UTC, merged