[최형택] Mission2: 모델링 완료
wecode-bootcamp-korea/29-westagram-backend-5-team pull request #9
Opened 2022-01-15 02:27 UTC by knuckles6974

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-위스타그램 모델링 완료 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-모델링 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- .

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-17 02:12 UTC, lordmyshepherd requested changes

2022-01-17 02:12 UTC, lordmyshepherd commented on students/hyeongtaek/westagram/users/models.py
> +
빈 줄은 지워주세요!

2022-01-17 02:12 UTC, lordmyshepherd commented on students/hyeongtaek/westagram/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2022-01-17 02:12 UTC, lordmyshepherd commented on students/hyeongtaek/westagram/users/models.py
> +class User(models.Model):
👍🏻

2022-01-17 02:12 UTC, lordmyshepherd commented on students/hyeongtaek/westagram/users/models.py
> +# Create your models here.
불필요한 주석은 지워주세요~

2022-01-18 03:00 UTC, bigfanoftim requested changes
현재 PR과 관련없는 코드들은 다른 브랜치에서 Push해서 PR 따로 만들어주세요. 기능별로 PR 올려주시면 됩니다.

2022-01-18 03:00 UTC, bigfanoftim commented on students/hyeongtaek/westagram/users/urls.py
> +
```suggestion
```

2022-01-18 03:00 UTC, bigfanoftim commented on students/hyeongtaek/westagram/users/views.py
> +            return JsonResponse({'message':'SUCCESS'},status=201)
```suggestion
```

2022-01-20 00:48 UTC, merged